name: Security Checks

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go
          queries: +security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          analyze-incremental: true

  dependency-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: 1
          severity: CRITICAL,HIGH

  go-lint:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main | grep '\.go$' || true)
          if [[ -n "$CHANGED_FILES" ]]; then
            golangci-lint run $CHANGED_FILES --timeout=5m
          else
            echo "No Go files changed."
          fi

  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Run Checkov
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main | grep '\.tf$' || true)
          if [[ -n "$CHANGED_FILES" ]]; then
            checkov -f $CHANGED_FILES --quiet
          else
            echo "No Terraform files changed."
          fi
